on:
  push:
  workflow_dispatch:

env:
  RELEASE_START: 100

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    container:
      image: ayufan/rock64-dockerfiles:trixie
      options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure version
      run: echo "VERSION=$(cat VERSION)-$(($RELEASE_START+$GITHUB_RUN_NUMBER))" >> $GITHUB_ENV
    - name: Cleanup old packages
      run: rm -f *.tar.xz
    - name: Install keyring
      run: make keyring
    - name: Build images
      run: make all
    - name: Release images
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        name: ${{ env.VERSION }}
        body: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        target_commitish: ${{ github.sha }}
        files: "*.tar.xz"
